sever:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:mysql://47.102.109.90:3306/shopping_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

#cms_*�����ݹ���ģ����ر�
#oms_*����������ģ����ر�
#pms_*����Ʒģ����ر�
#sms_*��Ӫ��ģ����ر�
#ums_*����Աģ����ر�
